version: '3.8'

services:
  # shake-client:
  #   image: xanderstrike/shake-client:latest
  #   container_name: shake-client
  #   volumes:
  #     - ./demoq3:/usr/share/nginx/html/demoq3
  #   ports:
  #     - "8081:80"
  shake-dev:
    image: nginx:latest
    container_name: shake-dev
    environment:
      - VIRTUAL_HOST=shake.standke.dev
      - LETSENCRYPT_HOST=shake.standke.dev
      - VIRTUAL_PORT=80
    volumes:
      - ./client:/usr/share/nginx/html
      - ./demoq3:/usr/share/nginx/html/demoq3
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
  shake-server:
    image: xanderstrike/shake-server:latest
    container_name: shake-server
    environment:
      - VIRTUAL_HOST=shake-peerserver.standke.dev
      - LETSENCRYPT_HOST=shake-peerserver.standke.dev
      - VIRTUAL_PORT=8080
    ports:
      - "8080:8080"
